[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"  # Ensures proper bundling

[build.environment]
  NODE_VERSION = "16"       # Netlify defaults to 14 (which can cause issues)

[dev]
  framework = "vite"
  targetPort = 5173
  command = "vite"
  publish = "dist"
  functionsPort = 9999 # port for functions emulator
  autoLaunch = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200